innodom_django/innodom_27_30_31_dop/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from api.views import (
    product_list,
    create_new_product,
    category_list,
    ProductApiView,
    AllProductsGenericView,
    CategoryViewSet,
    RatingViewSet,
    CommentViewSet,
    InfoProductGenericView,
    UserViewSet,
    ProductsAllPIView,
    ProductInfoGenericView,
    UserRegistrationGenericView
)
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
router = DefaultRouter()
router.register(r'category', CategoryViewSet)
router.register(r'rating', RatingViewSet)
router.register(r'comment', CommentViewSet)
router.register(r'user', UserViewSet)

urlpatterns = [
    path('product/', product_list),
    path('product-create/', create_new_product),
    path('category-list/', category_list),
    path('products/', ProductApiView.as_view()),
    path('products/<int:product_id>/', AllProductsGenericView.as_view()),
    path('info-product/<int:product_id>/', InfoProductGenericView.as_view()),
    path('products-all/<int:product_id>/', ProductInfoGenericView.as_view()),
    path('auth/register/', UserRegistrationGenericView.as_view()),
    path('token/', TokenObtainPairView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
] + router.urls

innodom_django/innodom_27_30_31_dop/config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('api/', include('api.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

innodom_django/innodom_27_30_31_dop/product/urls.py
from django.urls import path
from product.views import (
    get_all_products,
    create_new_product,
    update_product,
    get_product_info_by_product_id,
    delete_product
)

app_name = 'product'

urlpatterns = [
    path('', get_all_products, name='all-product'),
    path('create/', create_new_product, name='create-product'),
    path('<int:product_id>/', get_product_info_by_product_id, name='product-info'),
    path('<int:product_id>/update/', update_product, name='update-product'),
    path('<int:product_id>/delete/', delete_product, name='delete-product'),
]

innodom_django/innodom_27_30_31_dop/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'product/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'product/css/product.css' %}">
    <link rel="stylesheet" href="{% static 'product/css/product_forma.css' %}">
    <link rel="stylesheet" href="{% static 'product/css/product_info.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}Product</title>

</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'product:all-product' %}">MyApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'product:all-product' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'product:all-product' %}">Profile</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Product
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'product:all-product' %}">All</a></li>
            <li><a class="dropdown-item" href="{% url 'product:create-product' %}">Create</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Manage</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'product:create-product' %}" tabindex="-1">Add new product</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>