innodom_django/innodom_27_30_31_dop/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from api.views import (
    product_list,
    create_new_product,
    category_list,
    ProductApiView,
    AllProductsGenericView,
    CategoryViewSet,
    RatingViewSet,
    CommentViewSet,
    InfoProductGenericView,
    UserViewSet,
    ProductsAllPIView,
    ProductInfoGenericView,
    UserRegistrationGenericView
)
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
router = DefaultRouter()
router.register(r'category', CategoryViewSet)
router.register(r'rating', RatingViewSet)
router.register(r'comment', CommentViewSet)
router.register(r'user', UserViewSet)

urlpatterns = [
    path('product/', product_list),
    path('product-create/', create_new_product),
    path('category-list/', category_list),
    path('products/', ProductApiView.as_view()),
    path('products/<int:product_id>/', AllProductsGenericView.as_view()),
    path('info-product/<int:product_id>/', InfoProductGenericView.as_view()),
    path('products-all/<int:product_id>/', ProductInfoGenericView.as_view()),
    path('auth/register/', UserRegistrationGenericView.as_view()),
    path('token/', TokenObtainPairView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
] + router.urls

innodom_django/innodom_27_30_31_dop/config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('api/', include('api.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

innodom_django/innodom_27_30_31_dop/product/urls.py
from django.urls import path
from product.views import (
    get_all_products,
    create_new_product,
    update_product,
    get_product_info_by_product_id,
    delete_product
)

app_name = 'product'

urlpatterns = [
    path('', get_all_products, name='all-product'),
    path('create/', create_new_product, name='create-product'),
    path('<int:product_id>/', get_product_info_by_product_id, name='product-info'),
    path('<int:product_id>/update/', update_product, name='update-product'),
    path('<int:product_id>/delete/', delete_product, name='delete-product'),
]

innodom_django/innodom_27_30_31_dop/product/models.py
from django.db import models
from django.dispatch import receiver


class Category(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categorys'

    def __str__(self):
        return self.name

# Домашнее 30
# Создайте модели Product, Rating и Comment, где Product будет иметь отношение "один-ко-многим" к Rating и Comment.
class Rating(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name = 'Rating'
        verbose_name_plural = 'Ratings'

    def __str__(self):
        return self.rating


class Comment(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey(
        Category,
        null=True,
        blank=True,
        on_delete=models.DO_NOTHING
    )
    rating = models.ManyToManyField(
        Rating,
        null=True,
        blank=True,
        related_name='rating')
    comments = models.ManyToManyField(
        Comment,
        null=True,
        blank=True,
        related_name='comment'
    )
    prise = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.name

innodom_django/innodom_27_30_31_dop/product/forms.py
from product.models import Category, Product
from django.forms import (
    ModelForm,
    fields,
    ModelChoiceField,
)


class CreateProductForm(ModelForm):
    name = fields.CharField(max_length=50)
    category = ModelChoiceField(queryset=Category.objects.all())
    prise = fields.CharField(max_length=50)

    class Meta:
        model = Product
        fields = '__all__'


class ProductUpdateForm(ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'category', 'prise')

innodom_django/innodom_27_30_31_dop/product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from product.models import Product, Category
from product.forms import CreateProductForm, ProductUpdateForm


def home_page(request):
    return render(
        request=request,
        template_name='main.html'
    )


def get_all_products(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(
        request=request,
        template_name='product/all_products.html',
        context=context
    )


def create_new_product(request):
    categories = Category.objects.all()

    if request.method == 'POST':
        form = CreateProductForm(request.POST)
        if form.is_valid():
            product_data = form.cleaned_data
            Product.objects.create(**product_data)
            return redirect("product:all-product")
        context = {
            'form': form,
            'categories': categories
        }
    else:
        form = CreateProductForm()
        context = {
            'form': form,
            'categories': categories
        }

    return render(
        request=request,
        template_name='product/create_product.html',
        context=context
    )


def update_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    categories = Category.objects.all()

    if request.method == 'POST':
        form = ProductUpdateForm(request.POST, instance=product)

        if form.is_valid():
            form.save()
            return redirect("product:all-product")

        context = {
            'form': form,
            'categories': categories
        }

    else:
        form = ProductUpdateForm(instance=product)
        context = {
            'form': form,
            'categories': categories
        }

    return render(
        request=request,
        template_name='product/create_product.html',
        context=context
    )


def get_product_info_by_product_id(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    contex = {
        'product': product
    }

    return render(
        request=request,
        template_name='product/product_info.html',
        context=contex
    )


def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    product.delete()
    return redirect('product:all-product')

innodom_django/innodom_27_30_31_dop/templates/product/all_products.html
{% extends 'main.html' %}

{% block title %}
    All Product
{% endblock %}

{% block content %}
    <div class="products">
        {% for product in products %}
        <a href="{% url 'product:product-info' product.id %}" class="product-link">
            <div class="product">
            <h2>name: {{ product.name }}</h2>
            <h4>category: {{ product.category }}</h4>
            <h4><b>prise: {{ product.prise }}</b></h4>
            <h4><p>created: {{ product.created_at }}</p></h4>
        </div>
        </a>
        {% endfor %}
    </div>
{% endblock %}

innodom_django/innodom_27_30_31_dop/templates/product/create_product.html
{% extends 'main.html' %}
{% block title %}
    Create New Product
{% endblock %}

{% block content %}
    <div class="new-product-name">
        Create New Product
    </div>
    <div class="new-product-container">
        <form method="post">
            {% csrf_token %}

            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name="name" maxlength="25" placeholder="Name">
            </div>

            <div class="mb-3">
                <label for="category" class="form-label">Category</label>
                <select class="form-control" id="category" name="category">
                    <option value="" selected="">---</option> <!-- For optional category -->
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label for="prise" class="form-label">Prise</label>
                <input class="form-control" id="prise" name="prise" maxlength="15" placeholder="Prise">
            </div>

            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
{% endblock %}

innodom_django/innodom_27_30_31_dop/templates/product/product_info.html
{% extends 'main.html' %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
    <div class="product-content">
        <div class="product-block">
            <div class="product-info">
                <h2><span class="product-info-fields">Name: </span>{{ product.name }}</h2>
                <h4><span class="product-info-fields">Category: </span>{{ product.category }}</h4>
                <h4><span class="product-info-fields">Prise: </span><b>{{ product.prise }}</b></h4>
            </div>
            <div class="button-container">
                <a href="{% url 'product:update-product' product.id %}" class="update-button">Update</a>
                <a href="{% url 'product:delete-product' product.id %}" class="delete-button">Delete</a>
            </div>
        </div>
    </div>
{% endblock %}